config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'
  post :vote, to: 'votes#vote'
  get 'search/index'

  resources :comments, only: %i[create]

  resources :questions do
    resources :answers, only: %i[new create update destroy], shallow: true do
      member do
        post :favour
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:show, :create, :update, :destroy],
                            shallow: true
      end
    end
  end

  resources :collections, only: :destroy

  resources :awards, only: :index

  resources :subscriptions, only: [:create, :destroy]

  mount ActionCable.server => '/cable'
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_resource

  def destroy
    if current_user.author?(@resource)
      @attached.purge
      flash.now[:notice] = 'Your files successfully removed.'
    else
      flash.now[:alert] = 'Only owner can remove files of his resource.'
    end
  end

  private

  def load_resource
    @attached = ActiveStorage::Attachment.find(params[:id])
    entity = @attached.record_type.safe_constantize
    @resource = entity.joins(:files_attachments).where(
      active_storage_attachments: { id: @attached.id }
    ).first
  end
end

app/views/collections/destroy.js.erb
$('.<%= @resource.class.to_s.downcase %>-errors').html(
  "<%= render 'shared/errors', resource: @resource %>"
)
$('.notice').html("<%= flash[:notice] %>");

<% if @attached %>
  $("ul.<%= @resource.class.to_s.downcase %>-files").find(
    "li[data-file-id=<%= @attached.id %>]"
  ).remove()
<% end %>

app/views/collections/show.html.slim
- if resource.files.attached?
  ul class=(resource.class.to_s.downcase + '-files')
    - resource.files.each do |file|
      li data-file-id=file.id
        = link_to file.filename.to_s, url_for(file)
        - if can?(:destroy, resource)
          br
          = link_to 'Remove file', collection_path(file), method: :delete,
            remote: true