config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'
  post :vote, to: 'votes#vote'
  get 'search/index'

  resources :comments, only: %i[create]

  resources :questions do
    resources :answers, only: %i[new create update destroy], shallow: true do
      member do
        post :favour
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:show, :create, :update, :destroy],
                            shallow: true
      end
    end
  end

  resources :collections, only: :destroy

  resources :awards, only: :index

  resources :subscriptions, only: [:create, :destroy]

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Voteable
  include Commentable

  has_many_attached :files

  belongs_to :question
  belongs_to :user

  validates :body, presence: true

  scope :favourite, -> { where(favourite: true) }
  scope :unfavourite, -> { where(favourite: false) }
  default_scope { order(favourite: :desc) }

  def favour
    transaction do
      question.answers.favourite.update_all(favourite: false)
      update!(favourite: true)
      question.award&.update!(user: user)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: %i[new create]
  before_action :load_answer, only: %i[favour update destroy]

  after_action :publish_answer, only: %i[create]

  authorize_resource

  def favour
    if current_user.author?(@answer.question)
      @answer.favour
      @answers = @answer.question.answers
      flash.now[:notice] = 'Answer marked as favourite.'
    else
      flash.now[:alert] = 'Only question owner can make favourite the answer.'
    end
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user

    if @answer.save
      @answer.links.each(&:download!)
      Services::AnswerNotification.new.send_notification(@answer.question)
      flash.now[:notice] = 'Your answer successfully created.'
    else
      flash.now[:alert] = 'An error(s) occurred while saving answer'
    end
  end

  def update
    @question = @answer.question

    if current_user.author?(@answer)
      @answer.update(answer_params)
      flash.now[:notice] = 'Your answer successfully updated.'
    else
      flash.now[:alert] = 'Only owner can update his answer.'
    end
  end

  def destroy
    @question = @answer.question

    if current_user&.author?(@answer)
      @answer.destroy
      flash.now[:notice] = 'Answer successfully deleted.'
    else
      flash.now[:alert] = 'Only owner can delete his answer.'
    end
  end

  private

  # rubocop:disable Style/SymbolArray
  def answer_params
    params.require(:answer).permit(
      :body, files: [], links_attributes: [:id, :name, :url, :_destroy]
    )
  end
  # rubocop:enable Style/SymbolArray

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def links_attacher
    @answer.links.map do |l|
      if l.gist_content&.content
        { gist_content: l.gist_content.content }
      else
        { name: l.name, url: l.url }
      end
    end
  end

  def files_attacher
    @answer.files.map do |file|
      {
        id: file.id,
        name: file.filename.to_s,
        url: url_for(file)
      }
    end
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@question.id}/answers",
      answer: @answer,
      links: links_attacher,
      files: files_attacher
    )
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < BaseController
      before_action :load_question, only: %i[create]
      before_action :load_answer, only: %i[show update destroy]

      authorize_resource

      def show
        render json: @answer
      end

      def create
        @answer = @question.answers.build(answer_params)
        @answer.user = current_user

        if @answer.save
          render json: @answer
        else
          render json: @answer.errors, status: :unprocessable_entity
        end
      end

      def update
        if @answer.update(answer_params)
          render json: @answer
        else
          render json: @answer.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @answer.destroy
        render json: @answer
      end

      private

      # rubocop:disable Style/SymbolArray
      def answer_params
        params.require(:answer).permit(
          :body, files: [], links_attributes: [:id, :name, :url, :_destroy]
        )
      end
      # rubocop:enable Style/SymbolArray

      def load_question
        @question = Question.find(params[:question_id])
      end

      def load_answer
        @answer = Answer.with_attached_files.find(params[:id])
      end
    end
  end
end

app/views/answers/_answer.html.slim
- if answer.valid?
  br
  .answer data-answer-id="#{answer.id}" class=('favourite' if answer.favourite?)
    | Body:
    = answer.body
    .links
      ul
        = render answer.links
    = render template: 'collections/show', locals: { resource: answer }

    - if can?(:update, answer)
      p = link_to 'Edit', '#', class: 'edit-answer-link',
        data: { answer_id: answer.id }
      = render 'answers/form', entity: answer
      end
    div
      - if can?(:destroy, answer)
        p
          = link_to 'Delete Answer', answer_path(answer), method: :delete,
            remote: true
      - if can?(:favour, answer) && !answer.favourite?
        br
        = link_to 'Favourite answer', favour_answer_path(answer),
          method: :post, remote: true

  div class="answer-#{answer.id}-votes"
    = render 'votes/vote', resource: answer

  div class="new-answer-#{answer.id}-comment"
    - if can?(:create, Comment)
      = render 'comments/form', commentable: answer

  ul class="answer-#{answer.id}-comments"
    = render answer.comments

app/views/answers/_form.html.slim
- answer_id = entity.id unless entity.is_a?(Array)
= form_with model: entity, class: answer_id ? 'hidden' : 'new-answer',
  html: { id: "edit-answer-#{answer_id || 'new'}" } do |f|
  p
    = f.label :body, 'Your answer'
    = f.text_area :body
  div id=("answer-#{answer_id || 'new'}-links")
    = f.fields_for :links do |l|
      = render 'links/link_fields', f: l
    .links
      = link_to_add_association 'Add link for answer', f, :links,
        partial: 'links/link_fields'
  p
    = f.label :files
    = f.file_field :files, multiple: true
  p = f.submit answer_id ? 'Save' : 'Write'

app/views/answers/accept.js.erb
var oldAnswer = $('.accepted-answer').contents();

oldAnswer.appendTo('.answers');
$('.answer').filter(function(){
    return $(this).data('answerId') === <%= @answer.id %>
}).remove();

$('.accepted-answer').html("<%= j render @answer %>");

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");
$('.notice').html("<%= flash[:notice] %>");

<% if @answer.persisted? %>
  $('.answers').append("<%= j render @answer %>");
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>")
$('.notice').html("<%= flash[:notice] %>");

<% if @answer.errors.blank? %>
  $('.answers').html("<%= j render @question.answers %>");
<% end %>

app/views/answers/favour.js.erb
<% if @answers %>
  $('.answers').html("<%= j render @answers %>");
<% end %>

app/views/answers/remove_file.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>")
$('.notice').html("<%= flash[:notice] %>");

<% if @attached %>
  $("ul.answer-files").find("li[data-file-id=<%= @attached.id %>]").remove()
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>")
$('.notice').html("<%= flash[:notice] %>");

<% if @answer.errors.blank? %>
  $('.answers').html("<%= j render @question.answers %>");
<% end %>