config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'
  post :vote, to: 'votes#vote'
  get 'search/index'

  resources :comments, only: %i[create]

  resources :questions do
    resources :answers, only: %i[new create update destroy], shallow: true do
      member do
        post :favour
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:show, :create, :update, :destroy],
                            shallow: true
      end
    end
  end

  resources :collections, only: :destroy

  resources :awards, only: :index

  resources :subscriptions, only: [:create, :destroy]

  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :user_id, uniqueness: { scope: :question_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: :create
  before_action :load_subscription, only: :destroy

  def create
    authorize! :create, Subscription

    @subscription = @question.subscribe(current_user)
    if @subscription.errors.empty?
      flash.now[:notice] = 'You are subscribed for answer questions'
      render json: { id: @subscription.id, result: 'subscribe' }, status: :ok
    else
      render json: { errors: @subscription.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, Subscription

    @subscription.question.unsubscribe(current_user)
    if @subscription&.errors&.empty?
      flash.now[:notice] = 'You are unsubscribed for answer questions'
      render json: { id: @subscription.id, result: 'unsubscribe' }, status: :ok
    else
      render json: { errors: @subscription&.errors }, status: :unprocessable_entity
    end
  end

  private

  def load_question
    @question = Question.find(params['question_id'])
  end

  def load_subscription
    @subscription = current_user.subscriptions.find(params['id'])
  end
end

app/views/subscriptions/_subscription.html.slim
- if can?(:create, Subscription)
  = link_to 'Subscribe',
            subscriptions_path(question_id: @question),
            class: ['subscription-button',
                    'subscribe',
                    "#{'hidden' if current_user.subscribed?(@question)}"],
            method: :post, remote: true

br
- if can?(:destroy, Subscription)
  - subscription = current_user.subscriptions.find_by(question: @question)
  = link_to 'Unsubscribe',
            "#{subscription_path(subscription) if current_user.subscribed?(@question)}",
            class: ['subscription-button',
                    'unsubscribe',
                    "#{'hidden' unless current_user.subscribed?(@question)}"],
            method: :delete, remote: true